export const AllProduct = [
  {
    product_name: "Honey",
    source: "Family owned farm - Indonesia",
    product_form: "Liquid",
    category: "NATURAL SWEETENERS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: true,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Dates",
    source: "Indonesia & Yaman Varieties",
    product_form: "Liquid",
    category: "NATURAL SWEETENERS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: true,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Palm Sugar",
    source: "Family owned farm - Indonesia",
    botanical_name: "",
    product_form: "Liquid & Powder",
    category: "NATURAL SWEETENERS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: true,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Fructose",
    source: "Indonesia",
    botanical_name: "",
    product_form: "Liquid",
    category: "NATURAL SWEETENERS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: true,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Glucose",
    source: "Indonesia",
    botanical_name: "",
    product_form: "Liquid",
    category: "NATURAL SWEETENERS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: true,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Maltose",
    source: "Indonesia",
    botanical_name: "",
    product_form: "Liquid",
    category: "NATURAL SWEETENERS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: true,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Mung Bean",
    source: "",
    botanical_name: "Vigna radiata",
    product_form: "Powder",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: true,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Red Bean",
    source: "",
    botanical_name: "Phaseolus vulgaris",
    product_form: "Powder",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: true,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Soy Bean",
    source: "",
    botanical_name: "Glycine max",
    product_form: "Powder",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: true,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Adzuki Bean",
    source: "",
    botanical_name: "Vigna angularis",
    product_form: "Powder",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: true,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Cowpeas Bean",
    source: "",
    botanical_name: "Vigna unguiculata",
    product_form: "Powder",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: true,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "White Rice",
    source: "",
    botanical_name: "Oryza sativa",
    product_form: "Powder",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Red Rice",
    source: "",
    botanical_name: "Oryza glaberrima",
    product_form: "Powder",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Brown Rice",
    source: "",
    botanical_name: "Oryza sativa L.",
    product_form: "Powder",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "White Glutinous Rice",
    source: "",
    botanical_name: "Oryza sativa var. glutinosa",
    product_form: "Powder",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Black Glutinous Rice",
    source: "",
    botanical_name: "Oryza sativa var. glutinosa",
    product_form: "Powder",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Corn",
    source: "",
    botanical_name: "Zea mays",
    product_form: "Powder",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "White Sesame Seeds",
    source: "",
    botanical_name: "Sesamum indicum",
    product_form: "Whole Grains",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Black Sesame Seeds",
    source: "",
    botanical_name: "Sesamum indicum",
    product_form: "Whole Grains",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Purple Sweet Potato",
    source: "",
    botanical_name: "Ipomoea batatas L.",
    product_form: "Powder",
    category: "FRUIT & VEGETABLES",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Sweet Potato",
    source: "",
    botanical_name: "Ipomoea batatas L.",
    product_form: "Powder",
    category: "FRUIT & VEGETABLES",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Pumpkin",
    source: "",
    botanical_name: "Cucurbita",
    product_form: "Powder",
    category: "FRUIT & VEGETABLES",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Red Yeast Rice",
    source: "",
    botanical_name: "Monascus purpureus",
    product_form: "Powder",
    category: "FRUIT & VEGETABLES",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Ginseng",
    source: "",
    botanical_name: "Panax ginseng",
    product_form: "Powder",
    category: "FRUIT & VEGETABLES",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Acai Berry",
    source: "",
    botanical_name: "Euterpe oleracea",
    product_form: "Powder",
    category: "FRUIT & VEGETABLES",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Apple",
    source: "",
    botanical_name: "Malus spp.",
    product_form: "Powder",
    category: "FRUIT & VEGETABLES",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Mandarin Orange",
    source: "",
    botanical_name: "Citrus reticulata",
    product_form: "Powder",
    category: "FRUIT & VEGETABLES",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Avocado",
    source: "",
    botanical_name: "Persea americana",
    product_form: "Powder",
    category: "FRUIT & VEGETABLES",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Lactic Acid",
    source: "",
    botanical_name: "",
    manufacture: "Galactic Biochemichal",
    product_form: "Liquid",
    category: "NATURAL PRESERVATIVES / ANTI MICROBES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Buffer Lactic Acid",
    source: "",
    botanical_name: "",
    manufacture: "Galactic Biochemichal",
    product_form: "Liquid",
    category: "NATURAL PRESERVATIVES / ANTI MICROBES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Sodium Lactate",
    source: "",
    botanical_name: "",
    manufacture: "Galactic Biochemichal",
    product_form: "Liquid",
    category: "NATURAL PRESERVATIVES / ANTI MICROBES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Calcium Lactate",
    source: "",
    botanical_name: "",
    manufacture: "Galactic Biochemichal",
    product_form: "Liquid",
    category: "NATURAL PRESERVATIVES / ANTI MICROBES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Creatine Monohydrate",
    source: "",
    botanical_name: "",
    manufacture: "Shanghai Passiono",
    product_form: "Powder",
    category: "NATURAL ADDITIVES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Glucosamine",
    source: "",
    botanical_name: "",
    manufacture: "Shanghai Passiono",
    product_form: "Powder",
    category: "NATURAL ADDITIVES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Lycopene",
    source: "",
    botanical_name: "",
    manufacture: "Shanghai Passiono",
    product_form: "Powder",
    category: "NATURAL ADDITIVES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "L-Carmoisine",
    source: "",
    botanical_name: "",
    manufacture: "Shanghai Passiono",
    product_form: "Powder",
    category: "NATURAL ADDITIVES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "L-Lysine",
    source: "",
    botanical_name: "",
    manufacture: "Shanghai Passiono",
    product_form: "Powder",
    category: "NATURAL ADDITIVES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Isomalt",
    source: "",
    botanical_name: "",
    manufacture: "Shandong Lujian",
    product_form: "Powder",
    category: "NATURAL ADDITIVES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Cheese",
    source: "",
    botanical_name: "",
    manufacture: "Kerry Ingredients",
    product_form: "Powder",
    category: "FLAVOR ENHANCER",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Whey Permeate",
    source: "",
    botanical_name: "",
    manufacture: "Proliant Dairy",
    product_form: "Powder",
    category: "DAIRY PRODUCTS",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Non Dairy Creamer",
    source: "",
    botanical_name: "",
    manufacture: "Food Excellence Specialist",
    product_form: "Powder",
    category: "DAIRY PRODUCTS",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Sodium Casseinate",
    source: "",
    botanical_name: "",
    manufacture: "Tatura",
    product_form: "Powder",
    category: "DAIRY PRODUCTS",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Silica Dioxide",
    source: "",
    botanical_name: "",
    manufacture: "Evonik",
    product_form: "Powder",
    category: "OTHERS SPECIALTY",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Magnesium Sulphate",
    source: "",
    botanical_name: "",
    manufacture: "Kalisel Germany",
    product_form: "Powder",
    category: "OTHERS SPECIALTY",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    product_name: "Potassium Sulphate",
    source: "",
    botanical_name: "",
    manufacture: "Kalisel Germany",
    product_form: "Powder",
    category: "OTHERS SPECIALTY",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
];
