export const AllProduct = [
  {
    id: 1,
    product_name: "Honey",
    source: "Family owned farm - Indonesia",
    product_form: "Liquid",
    category: "NATURAL SWEETENERS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: true,
    new_product: false,
    images: [
      "/assets/image/products/honey/2.jpg",
      "/assets/image/products/honey/3.jpg",
      "/assets/image/products/honey/1.jpg",
      "/assets/image/products/honey/4.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 2,
    product_name: "Dates",
    source: "Indonesia & Yaman Varieties",
    product_form: "Liquid",
    category: "NATURAL SWEETENERS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: true,
    new_product: false,
    images: [
      "/assets/image/products/dates/3.jpg",
      "/assets/image/products/dates/1.jpg",
      "/assets/image/products/dates/2.jpg",
      "/assets/image/products/dates/4.jpg",
      "/assets/image/products/dates/5.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 3,
    product_name: "Palm Sugar",
    source: "Family owned farm - Indonesia",
    botanical_name: "",
    product_form: "Liquid & Powder",
    category: "NATURAL SWEETENERS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: true,
    new_product: false,
    images: [
      "/assets/image/products/brown-sugar/1.jpg",
      "/assets/image/products/brown-sugar/2.jpg",
      "/assets/image/products/brown-sugar/5.jpg",
      "/assets/image/products/brown-sugar/6.jpg",
      "/assets/image/products/brown-sugar/7.jpg",
      "/assets/image/products/brown-sugar/8.jpg",
      "/assets/image/products/brown-sugar/3.jpg",
      "/assets/image/products/brown-sugar/4.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 4,
    product_name: "Fructose",
    source: "Indonesia",
    botanical_name: "",
    product_form: "Liquid",
    category: "NATURAL SWEETENERS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: true,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 5,
    product_name: "Glucose",
    source: "Indonesia",
    botanical_name: "",
    product_form: "Liquid",
    category: "NATURAL SWEETENERS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: true,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 6,
    product_name: "Maltose",
    source: "Indonesia",
    botanical_name: "",
    product_form: "Liquid",
    category: "NATURAL SWEETENERS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: true,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 7,
    product_name: "Mung Bean",
    source: "",
    botanical_name: "Vigna radiata",
    product_form: "Powder",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: true,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 8,
    product_name: "Red Bean",
    source: "",
    botanical_name: "Phaseolus vulgaris",
    product_form: "Powder",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: true,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 9,
    product_name: "Soy Bean",
    source: "",
    botanical_name: "Glycine max",
    product_form: "Powder",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: true,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 10,
    product_name: "Adzuki Bean",
    source: "",
    botanical_name: "Vigna angularis",
    product_form: "Powder",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: true,
    images: [
      "/assets/image/products/adzuki-bean/3.jpg",
      "/assets/image/products/adzuki-bean/2.jpg",
      "/assets/image/products/adzuki-bean/1.jpg",
      "/assets/image/products/adzuki-bean/4.jpg",
      "/assets/image/products/adzuki-bean/5.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 11,
    product_name: "Cowpeas Bean",
    source: "",
    botanical_name: "Vigna unguiculata",
    product_form: "Powder",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: true,
    images: [
      "/assets/image/products/cowpeas-bean/5.jpg",
      "/assets/image/products/cowpeas-bean/1.jpg",
      "/assets/image/products/cowpeas-bean/2.jpg",
      "/assets/image/products/cowpeas-bean/3.jpg",
      "/assets/image/products/cowpeas-bean/4.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 12,
    product_name: "White Rice",
    source: "",
    botanical_name: "Oryza sativa",
    product_form: "Powder",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 13,
    product_name: "Red Rice",
    source: "",
    botanical_name: "Oryza glaberrima",
    product_form: "Powder",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 14,
    product_name: "Brown Rice",
    source: "",
    botanical_name: "Oryza sativa L.",
    product_form: "Powder",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    images: [
      "/assets/image/products/brown-rice/3.jpg",
      "/assets/image/products/brown-rice/1.jpg",
      "/assets/image/products/brown-rice/2.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 15,
    product_name: "White Glutinous Rice",
    source: "",
    botanical_name: "Oryza sativa var. glutinosa",
    product_form: "Powder",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 16,
    product_name: "Black Glutinous Rice",
    source: "",
    botanical_name: "Oryza sativa var. glutinosa",
    product_form: "Powder",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 17,
    product_name: "Corn",
    source: "",
    botanical_name: "Zea mays",
    product_form: "Powder",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 18,
    product_name: "White Sesame Seeds",
    source: "",
    botanical_name: "Sesamum indicum",
    product_form: "Whole Grains",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 19,
    product_name: "Black Sesame Seeds",
    source: "",
    botanical_name: "Sesamum indicum",
    product_form: "Whole Grains",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 20,
    product_name: "Purple Sweet Potato",
    source: "",
    botanical_name: "Ipomoea batatas L.",
    product_form: "Powder",
    category: "FRUIT & VEGETABLES",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 21,
    product_name: "Sweet Potato",
    source: "",
    botanical_name: "Ipomoea batatas L.",
    product_form: "Powder",
    category: "FRUIT & VEGETABLES",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 22,
    product_name: "Pumpkin",
    source: "",
    botanical_name: "Cucurbita",
    product_form: "Powder",
    category: "FRUIT & VEGETABLES",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 23,
    product_name: "Red Yeast Rice",
    source: "",
    botanical_name: "Monascus purpureus",
    product_form: "Powder",
    category: "FRUIT & VEGETABLES",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 24,
    product_name: "Ginseng",
    source: "",
    botanical_name: "Panax ginseng",
    product_form: "Powder",
    category: "FRUIT & VEGETABLES",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 25,
    product_name: "Acai Berry",
    source: "",
    botanical_name: "Euterpe oleracea",
    product_form: "Powder",
    category: "FRUIT & VEGETABLES",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 26,
    product_name: "Apple",
    source: "",
    botanical_name: "Malus spp.",
    product_form: "Powder",
    category: "FRUIT & VEGETABLES",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 27,
    product_name: "Mandarin Orange",
    source: "",
    botanical_name: "Citrus reticulata",
    product_form: "Powder",
    category: "FRUIT & VEGETABLES",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 28,
    product_name: "Avocado",
    source: "",
    botanical_name: "Persea americana",
    product_form: "Powder",
    category: "FRUIT & VEGETABLES",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 29,
    product_name: "Lactic Acid",
    source: "",
    botanical_name: "",
    manufacture: "Galactic Biochemichal",
    product_form: "Liquid",
    category: "NATURAL PRESERVATIVES / ANTI MICROBES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 30,
    product_name: "Buffer Lactic Acid",
    source: "",
    botanical_name: "",
    manufacture: "Galactic Biochemichal",
    product_form: "Liquid",
    category: "NATURAL PRESERVATIVES / ANTI MICROBES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 31,
    product_name: "Sodium Lactate",
    source: "",
    botanical_name: "",
    manufacture: "Galactic Biochemichal",
    product_form: "Liquid",
    category: "NATURAL PRESERVATIVES / ANTI MICROBES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 32,
    product_name: "Calcium Lactate",
    source: "",
    botanical_name: "",
    manufacture: "Galactic Biochemichal",
    product_form: "Liquid",
    category: "NATURAL PRESERVATIVES / ANTI MICROBES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 33,
    product_name: "Creatine Monohydrate",
    source: "",
    botanical_name: "",
    manufacture: "Shanghai Passiono",
    product_form: "Powder",
    category: "NATURAL ADDITIVES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 34,
    product_name: "Glucosamine",
    source: "",
    botanical_name: "",
    manufacture: "Shanghai Passiono",
    product_form: "Powder",
    category: "NATURAL ADDITIVES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 35,
    product_name: "Lycopene",
    source: "",
    botanical_name: "",
    manufacture: "Shanghai Passiono",
    product_form: "Powder",
    category: "NATURAL ADDITIVES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 36,
    product_name: "L-Carmoisine",
    source: "",
    botanical_name: "",
    manufacture: "Shanghai Passiono",
    product_form: "Powder",
    category: "NATURAL ADDITIVES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 37,
    product_name: "L-Lysine",
    source: "",
    botanical_name: "",
    manufacture: "Shanghai Passiono",
    product_form: "Powder",
    category: "NATURAL ADDITIVES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 38,
    product_name: "Isomalt",
    source: "",
    botanical_name: "",
    manufacture: "Shandong Lujian",
    product_form: "Powder",
    category: "NATURAL ADDITIVES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 39,
    product_name: "Cheese",
    source: "",
    botanical_name: "",
    manufacture: "Kerry Ingredients",
    product_form: "Powder",
    category: "FLAVOR ENHANCER",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 40,
    product_name: "Whey Permeate",
    source: "",
    botanical_name: "",
    manufacture: "Proliant Dairy",
    product_form: "Powder",
    category: "DAIRY PRODUCTS",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 41,
    product_name: "Non Dairy Creamer",
    source: "",
    botanical_name: "",
    manufacture: "Food Excellence Specialist",
    product_form: "Powder",
    category: "DAIRY PRODUCTS",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 42,
    product_name: "Sodium Casseinate",
    source: "",
    botanical_name: "",
    manufacture: "Tatura",
    product_form: "Powder",
    category: "DAIRY PRODUCTS",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 43,
    product_name: "Silica Dioxide",
    source: "",
    botanical_name: "",
    manufacture: "Evonik",
    product_form: "Powder",
    category: "OTHERS SPECIALTY",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 44,
    product_name: "Magnesium Sulphate",
    source: "",
    botanical_name: "",
    manufacture: "Kalisel Germany",
    product_form: "Powder",
    category: "OTHERS SPECIALTY",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 45,
    product_name: "Potassium Sulphate",
    source: "",
    botanical_name: "",
    manufacture: "Kalisel Germany",
    product_form: "Powder",
    category: "OTHERS SPECIALTY",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
];
