export const AllProduct = [
  {
    id: 1,
    product_name: "Honey",
    source: "Sumatera, Riau, Borneo / Kalimantan, Java - Indonesia ",
    product_form: "Liquid",
    category: "NATURAL SWEETENERS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: true,
    new_product: false,
    images: [
      "/assets/image/products/honey/1.jpg",
      "/assets/image/products/honey/2.jpg",
      "/assets/image/products/honey/3.jpg",
      "/assets/image/products/honey/4.jpg",
    ],
    description:
      "Explore the all series of Indonesia honey to creating a healthier sweetener.",
  },
  {
    id: 2,
    product_name: "Dates",
    source: "Indonesia & Yaman Varieties",
    product_form: "Liquid",
    category: "NATURAL SWEETENERS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    images: [
      "/assets/image/products/dates/3.jpg",
      "/assets/image/products/dates/1.jpg",
      "/assets/image/products/dates/2.jpg",
      "/assets/image/products/dates/4.jpg",
      "/assets/image/products/dates/5.jpg",
    ],
    description:
      "Mainly used in beverage, cake – pastry products, cream filling.",
  },
  {
    id: 3,
    product_name: "Palm Sugar",
    source: "Sumatera, Java - Indonesia",
    botanical_name: "",
    product_form: "Liquid & Powder",
    category: "NATURAL SWEETENERS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: true,
    new_product: false,
    images: [
      "/assets/image/products/brown-sugar/1.jpg",
      "/assets/image/products/brown-sugar/2.jpg",
      "/assets/image/products/brown-sugar/5.jpg",
      "/assets/image/products/brown-sugar/6.jpg",
      "/assets/image/products/brown-sugar/7.jpg",
      "/assets/image/products/brown-sugar/8.jpg",
      "/assets/image/products/brown-sugar/3.jpg",
      "/assets/image/products/brown-sugar/4.jpg",
    ],
    description:
      "Kick ‘in up your product with the famous Indonesia sugar. Comes with floral aroma, smooth and unique afternote. Mainly used in beverage, snack, ice cream, and cake – pastry products.",
  },
  {
    id: 4,
    product_name: "Fructose",
    source: "Indonesia",
    botanical_name: "",
    product_form: "Liquid",
    category: "NATURAL SWEETENERS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    images: [
      "/assets/image/products/fructose-glucose-maltose/1.jpg",
      "/assets/image/products/fructose-glucose-maltose/2.jpg",
      "/assets/image/products/fructose-glucose-maltose/3.jpg",
      "/assets/image/products/fructose-glucose-maltose/4.jpg",
      "/assets/image/products/fructose-glucose-maltose/5.jpg",
      "/assets/image/products/fructose-glucose-maltose/6.jpg",
      "/assets/image/products/fructose-glucose-maltose/7.jpg",
      "/assets/image/products/fructose-glucose-maltose/8.jpg",
      "/assets/image/products/fructose-glucose-maltose/9.jpg",
    ],
    description:
      "Mainly used in beverage, ice cream, and cake – pastry products.",
  },
  {
    id: 5,
    product_name: "Glucose",
    source: "Indonesia",
    botanical_name: "",
    product_form: "Liquid",
    category: "NATURAL SWEETENERS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    images: [
      "/assets/image/products/fructose-glucose-maltose/4.jpg",
      "/assets/image/products/fructose-glucose-maltose/5.jpg",
      "/assets/image/products/fructose-glucose-maltose/6.jpg",
      "/assets/image/products/fructose-glucose-maltose/7.jpg",
      "/assets/image/products/fructose-glucose-maltose/8.jpg",
      "/assets/image/products/fructose-glucose-maltose/9.jpg",
      "/assets/image/products/fructose-glucose-maltose/1.jpg",
      "/assets/image/products/fructose-glucose-maltose/2.jpg",
      "/assets/image/products/fructose-glucose-maltose/3.jpg",
    ],
    description:
      "Mainly used in beverage, ice cream, and cake – pastry products.",
  },
  {
    id: 6,
    product_name: "Maltose",
    source: "Indonesia",
    botanical_name: "",
    product_form: "Liquid",
    category: "NATURAL SWEETENERS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: true,
    images: [
      "/assets/image/products/fructose-glucose-maltose/7.jpg",
      "/assets/image/products/fructose-glucose-maltose/8.jpg",
      "/assets/image/products/fructose-glucose-maltose/9.jpg",
      "/assets/image/products/fructose-glucose-maltose/1.jpg",
      "/assets/image/products/fructose-glucose-maltose/2.jpg",
      "/assets/image/products/fructose-glucose-maltose/3.jpg",
      "/assets/image/products/fructose-glucose-maltose/4.jpg",
      "/assets/image/products/fructose-glucose-maltose/5.jpg",
      "/assets/image/products/fructose-glucose-maltose/6.jpg",
    ],
    description:
      "Mainly used in beverage, ice cream, and cake – pastry products.",
  },
  {
    id: 7,
    product_name: "Mung Bean",
    source: "",
    botanical_name: "Vigna radiata",
    product_form: "Powder, Whole Grains",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,

    new_product: true,
    images: [
      "/assets/image/products/mung-bean/1.jpg",
      "/assets/image/products/mung-bean/2.jpg",
      "/assets/image/products/mung-bean/3.jpg",
      "/assets/image/products/mung-bean/4.jpg",
    ],
    description:
      "The famous meal replacer with high protein and fibres contain. Mainly used in soft ice cream, beverages, cake – pastry, and improving the body taste.",
  },
  {
    id: 8,
    product_name: "Red Bean",
    source: "",
    botanical_name: "Phaseolus vulgaris",
    product_form: "Powder, Whole Grains",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: true,
    images: [
      "/assets/image/products/red-bean/3.jpg",
      "/assets/image/products/red-bean/4.jpg",
      "/assets/image/products/red-bean/5.jpg",
      "/assets/image/products/red-bean/1.jpg",
      "/assets/image/products/red-bean/2.jpg",
    ],
    description:
      "One of the high sources of protein, dietary fibre. Mainly used in soft ice cream, beverages, cake – pastry, and improving the body taste.",
  },
  {
    id: 9,
    product_name: "Soy Bean",
    source: "",
    botanical_name: "Glycine max",
    product_form: "Powder, Whole Grains",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: true,
    images: [
      "/assets/image/products/soy-bean/1.jpg",
      "/assets/image/products/soy-bean/2.jpg",
      "/assets/image/products/soy-bean/3.jpg",
      "/assets/image/products/soy-bean/4.jpg",
      "/assets/image/products/soy-bean/5.jpg",
      "/assets/image/products/soy-bean/6.jpg",
      "/assets/image/products/soy-bean/7.jpg",
      "/assets/image/products/soy-bean/8.jpg",
      "/assets/image/products/soy-bean/9.jpg",
    ],
    description:
      "Improving texture with high source of fibre. Mainly used in beverages, cake, and snack",
  },
  {
    id: 10,
    product_name: "Adzuki Bean",
    source: "",
    botanical_name: "Vigna angularis",
    product_form: "Powder, Whole Grains",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: true,
    images: [
      "/assets/image/products/adzuki-bean/3.jpg",
      "/assets/image/products/adzuki-bean/2.jpg",
      "/assets/image/products/adzuki-bean/1.jpg",
      "/assets/image/products/adzuki-bean/4.jpg",
      "/assets/image/products/adzuki-bean/5.jpg",
    ],
    description:
      "As a part family of Red Bean, this Adzuki Bean also contains high sources of protein, dietary fibre.  Softer skin profile makes it the best choice for ice cream. Mainly used in soft ice cream, beverages, cake – pastry, and improving the body taste.",
  },
  {
    id: 11,
    product_name: "Cowpeas Bean",
    source: "",
    botanical_name: "Vigna unguiculata",
    product_form: "Powder, Whole Grains",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: true,
    images: [
      "/assets/image/products/cowpeas-bean/5.jpg",
      "/assets/image/products/cowpeas-bean/1.jpg",
      "/assets/image/products/cowpeas-bean/2.jpg",
      "/assets/image/products/cowpeas-bean/3.jpg",
      "/assets/image/products/cowpeas-bean/4.jpg",
    ],
    description:
      "The highest source of protein in our collection, makes it the best choice as meal replacer. Mainly used in snack, cake – pastry products",
  },
  {
    id: 12,
    product_name: "White Rice",
    source: "",
    botanical_name: "Oryza sativa",
    product_form: "Powder, Whole Grains",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    images: [
      "/assets/image/products/w-rice/2.jpg",
      "/assets/image/products/w-rice/1.jpg",
      "/assets/image/products/w-rice/3.jpg",
      "/assets/image/products/w-rice/4.jpg",
      "/assets/image/products/w-rice/5.jpg",
    ],
    description:
      "Mainly used in snack, cake – pastry products to improve the texture and bold taste.",
  },
  {
    id: 13,
    product_name: "Red Rice",
    source: "",
    botanical_name: "Oryza glaberrima",
    product_form: "Powder",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,

    new_product: false,
    images: [
      "/assets/image/products/red-rice/2.jpg",
      "/assets/image/products/red-rice/1.jpg",
      "/assets/image/products/red-rice/3.jpg",
      "/assets/image/products/red-rice/4.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 14,
    product_name: "Brown Rice",
    source: "",
    botanical_name: "Oryza sativa L.",
    product_form: "Powder, Whole Grains",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    images: [
      "/assets/image/products/brown-rice/3.jpg",
      "/assets/image/products/brown-rice/1.jpg",
      "/assets/image/products/brown-rice/2.jpg",
    ],
    description:
      "The better sides of rice with higher source of fibre. Mainly used for meal replacer, beverage, and cake - pastry",
  },
  {
    id: 15,
    product_name: "White Glutinous Rice",
    source: "",
    botanical_name: "Oryza sativa var. glutinosa",
    product_form: "Powder, Whole Grains",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    images: [
      "/assets/image/products/white-glutin/1.jpg",
      "/assets/image/products/white-glutin/2.jpg",
    ],
    description:
      "Mainly used in cake – pastry products.",
  },
  {
    id: 16,
    product_name: "Black Glutinous Rice",
    source: "",
    botanical_name: "Oryza sativa var. glutinosa",
    product_form: "Powder, Whole Grains ",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,

    new_product: false,
    images: [
      "/assets/image/products/black-glutin/1.jpg",
      "/assets/image/products/black-glutin/2.jpg",
    ],
    description:
      "Not only for cake-pastry products, our product can be used for beverage, and meal replacement with high fibre contents.",
  },
  {
    id: 17,
    product_name: "Corn",
    source: "",
    botanical_name: "Zea mays",
    product_form: "Powder, Whole Grains",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    images: [
      "/assets/image/products/corn/3.jpg",
      "/assets/image/products/corn/1.jpg",
      "/assets/image/products/corn/2.jpg",
    ],
    description:
      "Mainly used in snack , cake – pastry products.",
  },
  {
    id: 18,
    product_name: "White Sesame Seeds",
    source: "",
    botanical_name: "Sesamum indicum",
    product_form: "Whole Grains, Roasted, Raw",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: true,
    new_product: false,
    images: [
      "/assets/image/products/white-sesame-seeds/2.jpg",
      "/assets/image/products/white-sesame-seeds/3.jpg",
      "/assets/image/products/white-sesame-seeds/1.jpg",
      "/assets/image/products/white-sesame-seeds/4.jpg",
    ],
    description:
      "Enrich your taste and aroma just with couple drops. Available in White series.",
  },
  {
    id: 19,
    product_name: "Black Sesame Seeds",
    source: "",
    botanical_name: "Sesamum indicum",
    product_form: "Whole Grains, Roasted, Raw",
    category: "BEANS & GRAINS",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    images: [
      "/assets/image/products/black-sesame-seeds/2.jpg",
      "/assets/image/products/black-sesame-seeds/3.jpg",
      "/assets/image/products/black-sesame-seeds/1.jpg",
      "/assets/image/products/black-sesame-seeds/4.jpg",
    ],
    description:
      "Enrich your taste and aroma just with couple drops. Available in Black series.",
  },
  {
    id: 20,
    product_name: "Purple Sweet Potato",
    source: "",
    botanical_name: "Ipomoea batatas L.",
    product_form: "Powder",
    category: "FRUIT & VEGETABLES",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: true,
    new_product: false,
    images: [
      "/assets/image/products/fruit-vegie/13.jpg",
      "/assets/image/products/fruit-vegie/20.jpg",
      "/assets/image/products/fruit-vegie/19.jpg",
      "/assets/image/products/fruit-vegie/18.jpg",
    ],
    description:
      "The richest nutritional benefit to improve your healthier meals.  Without any preservatives and colouring agent added. Mainly used in beverage, ice cream, cake – pastry, and cream filling.",
  },
  {
    id: 21,
    product_name: "Sweet Potato",
    source: "",
    botanical_name: "Ipomoea batatas L.",
    product_form: "Powder",
    category: "FRUIT & VEGETABLES",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    images: ["/assets/image/products/fruit-vegie/14.jpg"],
    description:
      "The richest nutritional benefit to improve your healthier meals.  Without any preservatives and colouring agent added. Mainly used in beverage, ice cream, cake – pastry, and cream filling.",
  },
  {
    id: 22,
    product_name: "Pumpkin",
    source: "",
    botanical_name: "Cucurbita",
    product_form: "Powder",
    category: "FRUIT & VEGETABLES",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    images: ["/assets/image/products/fruit-vegie/23.jpg"],
    description:
      "Mainly used in beverage, ice cream, cake – pastry, and snack products",
  },
  {
    id: 23,
    product_name: "Red Yeast Rice",
    source: "",
    botanical_name: "Monascus purpureus",
    product_form: "Powder",
    category: "FRUIT & VEGETABLES",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    images: ["/assets/image/products/fruit-vegie/7.jpg"],
    description:
      "Boost your colour appearance with natural red colour from our red yeast rice. Mainly used in beverage, ice cream, cake – pastry.",
  },
  {
    id: 24,
    product_name: "Ginseng",
    source: "",
    botanical_name: "Panax ginseng",
    product_form: "Powder",
    category: "FRUIT & VEGETABLES",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    images: ["/assets/image/products/fruit-vegie/24.jpg"],
    description:
      "The famous healthy ginseng are available in our collection. Mainly used in beverage, and healthy drinks.",
  },
  {
    id: 25,
    product_name: "Acai Berry",
    source: "",
    botanical_name: "Euterpe oleracea",
    product_form: "Powder",
    category: "FRUIT & VEGETABLES",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    images: ["/assets/image/products/fruit-vegie/25.jpg"],
    description:
      "The most powerful antioxidant components. Mainly used in beverage products.",
  },
  {
    id: 26,
    product_name: "Apple",
    source: "",
    botanical_name: "Malus spp.",
    product_form: "Powder",
    category: "FRUIT & VEGETABLES",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    images: [
      "/assets/image/products/fruit-vegie/1.jpg",
      "/assets/image/products/fruit-vegie/2.jpg",
    ],
    description:
      "Mainly used in beverage, cake – pastry products.",
  },
  {
    id: 27,
    product_name: "Mandarin Orange",
    source: "",
    botanical_name: "Citrus reticulata",
    product_form: "Powder",
    category: "FRUIT & VEGETABLES",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    images: ["/assets/image/products/fruit-vegie/26.jpg"],
    description:
      "Mainly used in beverage, ice cream, and cake – pastry products.",
  },
  {
    id: 28,
    product_name: "Avocado",
    source: "",
    botanical_name: "Persea americana",
    product_form: "Powder",
    category: "FRUIT & VEGETABLES",
    development_bussines: "100% NATURAL FROM OUR FAMILY OWNED FARM",
    best_seller: false,
    new_product: false,
    images: [
      "/assets/image/products/fruit-vegie/9.jpg",
      "/assets/image/products/fruit-vegie/10.jpg",
      "/assets/image/products/fruit-vegie/11.jpg",
    ],
    description:
      "Mainly used in beverage, ice cream, and cake – pastry products.",
  },
  {
    id: 29,
    product_name: "Lactic Acid",
    source: "",
    botanical_name: "",
    manufacture: "Galactic Biochemichal",
    product_form: "Liquid",
    category: "NATURAL PRESERVATIVES / ANTI MICROBES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: true,
    new_product: false,
    images: ["/assets/image/products/anti-microbes/17.jpg"],
    description:
      "Improving your product shelf life, and taste along with nutritional added.",
  },
  {
    id: 30,
    product_name: "Buffer Lactic Acid",
    source: "",
    botanical_name: "",
    manufacture: "Galactic Biochemichal",
    product_form: "Liquid",
    category: "NATURAL PRESERVATIVES / ANTI MICROBES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    images: ["/assets/image/products/anti-microbes/11.jpg"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 31,
    product_name: "Sodium Lactate",
    source: "",
    botanical_name: "",
    manufacture: "Galactic Biochemichal",
    product_form: "Liquid",
    category: "NATURAL PRESERVATIVES / ANTI MICROBES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    images: ["/assets/image/products/anti-microbes/11.jpg"],
    description:
      "Improving your product shelf life, and taste along with nutritional added.",
  },
  {
    id: 32,
    product_name: "Calcium Lactate",
    source: "",
    botanical_name: "",
    manufacture: "Galactic Biochemichal",
    product_form: "Liquid",
    category: "NATURAL PRESERVATIVES / ANTI MICROBES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    images: ["/assets/image/products/anti-microbes/11.jpg"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 33,
    product_name: "Creatine Monohydrate",
    source: "",
    botanical_name: "",
    manufacture: "Shanghai Passiono",
    product_form: "Powder",
    category: "NATURAL ADDITIVES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    images: ["/assets/image/products/natural-add/1.jpg"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 34,
    product_name: "Glucosamine",
    source: "",
    botanical_name: "",
    manufacture: "Shanghai Passiono",
    product_form: "Powder",
    category: "NATURAL ADDITIVES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    images: ["/assets/image/products/natural-add/2.jpg"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 35,
    product_name: "Lycopene",
    source: "",
    botanical_name: "",
    manufacture: "Shanghai Passiono",
    product_form: "Powder",
    category: "NATURAL ADDITIVES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    images: ["/assets/image/products/natural-add/3.jpg"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 36,
    product_name: "L-Carmoisine",
    source: "",
    botanical_name: "",
    manufacture: "Shanghai Passiono",
    product_form: "Powder",
    category: "NATURAL ADDITIVES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    images: ["/assets/image/products/natural-add/4.jpg"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 37,
    product_name: "L-Lysine",
    source: "",
    botanical_name: "",
    manufacture: "Shanghai Passiono",
    product_form: "Powder",
    category: "NATURAL ADDITIVES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    images: ["/assets/image/products/natural-add/5.jpg"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 38,
    product_name: "Isomalt",
    source: "",
    botanical_name: "",
    manufacture: "Shandong Lujian",
    product_form: "Powder",
    category: "NATURAL ADDITIVES",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    images: ["/assets/image/products/natural-add/6.jpg"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 39,
    product_name: "Cheese",
    source: "",
    botanical_name: "",
    manufacture: "Kerry Ingredients",
    product_form: "Powder",
    category: "FLAVOR ENHANCER",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    images: [
      "/assets/image/products/flavor-ench/1.jpg",
      "/assets/image/products/flavor-ench/2.jpg",
      "/assets/image/products/flavor-ench/3.jpg",
      "/assets/image/products/flavor-ench/4.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 40,
    product_name: "Whey Permeate",
    source: "",
    botanical_name: "",
    manufacture: "Proliant Dairy",
    product_form: "Powder",
    category: "DAIRY PRODUCTS",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    images: ["/assets/image/products/dairy/3.jpg"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 41,
    product_name: "Non Dairy Creamer",
    source: "",
    botanical_name: "",
    manufacture: "Food Excellence Specialist",
    product_form: "Powder",
    category: "DAIRY PRODUCTS",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    images: ["/assets/image/products/dairy/5.jpg"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 42,
    product_name: "Sodium Casseinate",
    source: "",
    botanical_name: "",
    manufacture: "Tatura",
    product_form: "Powder",
    category: "DAIRY PRODUCTS",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    images: ["/assets/image/products/dairy/2.jpg"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 43,
    product_name: "Silica Dioxide",
    source: "",
    botanical_name: "",
    manufacture: "Evonik",
    product_form: "Powder",
    category: "OTHERS SPECIALTY",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    images: ["/assets/image/products/other/1.jpg"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 44,
    product_name: "Magnesium Sulphate",
    source: "",
    botanical_name: "",
    manufacture: "Kalisel Germany",
    product_form: "Powder",
    category: "OTHERS SPECIALTY",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    images: ["/assets/image/products/other/2.jpg"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
  {
    id: 45,
    product_name: "Potassium Sulphate",
    source: "",
    botanical_name: "",
    manufacture: "Kalisel Germany",
    product_form: "Powder",
    category: "OTHERS SPECIALTY",
    development_bussines: "INTERNATIONAL PARTNERSHIP",
    best_seller: false,
    new_product: false,
    images: ["/assets/image/products/other/3.jpg"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna.",
  },
];
